### PR TITLE
Look for existing wallets before jumping on on-boarding

### LINKED ISSUE #177: Wallets created using the command line utility not found
# Software information
Build info:
- Version: 0.1.0 - unknown
- Commit hash: 7f9e335 

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered
I had a wallet set up using the command line wallet https://github.com/vegaprotocol/vegawallet in the default path.

# Observed behaviour
Upon launch I got asked to create new wallet or restore using passphrase:
image

I used "use recovery" and then put in the name of an existing wallet (thinking I won't have to update password in the browser if I use the same name and password). At this point I got told "wallet of the same name exists". True.

# Expected behaviour
If there are wallets that were created from command line and that live under the same path then show them. OR use different config directory by default.

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #177

### CODE REVIEW

File: frontend/src/contexts/global/global-actions.ts [hunk 1]
```diff
@@ -20,30 +20,32 @@ export function initAppAction() {
     try {
       const isInit = await Service.IsAppInitialised()
 
-      if (IS_TEST_MODE && !isInit) {
+      if (!isInit) {
```
Comment (mattrussell36) [inline frontend/src/contexts/global/global-actions.ts:23]: Hm I don't think we should call IniitaliseApp here. The init _should_ happen in the onboard flow.. 🤔

Comment (mattrussell36) [reply frontend/src/contexts/global/global-actions.ts:23]: I think the previous condition was correct. Only initialize if not already initialized AND in test mode. That way for tests we can navigate to different pages regardless of whether you are initialized without triggering the onboarding flow.

Otherwise if you aren't initialized always go to onboarding..

Comment (mattrussell36) [reply frontend/src/contexts/global/global-actions.ts:23]: Hm I'm not sure on my above comment looking into I more I can see why the change is necessary.

File: frontend/src/components/button-group/button-group.tsx [hunk 2]
```diff
@@ -24,12 +24,14 @@ export function ButtonGroup({
       }}
     >
       {React.Children.map(children, child => {
-        return React.cloneElement(child as any, {
-          style: {
-            flexGrow: 1,
-            flexBasis: 0
-          }
-        })
+        if (child) {
```
Comment (sam-keen) [inline frontend/src/components/button-group/button-group.tsx:27]: I don't think this check is necessary. React.children.map will only call the function on each child if children is an array, and would already have returned a null of undefined if not. Perhaps checking that children has a length greater than 0 would suffice? i.e. 
`{ children.length > 0 && React.Children.map(children, child => {`

Comment (ValentinTrinque) [reply frontend/src/components/button-group/button-group.tsx:27]: Yes indeed. And I don't think we event need to verify `children.length > 0` . The `map()` function is not supposed to trigger the closure if the collection is empty.

Comment (sam-keen) [reply frontend/src/components/button-group/button-group.tsx:27]: That's right, the condition the map function will be attempted and return a null or undefined, that would be fine too.

Comment (mattrussell36) [reply frontend/src/components/button-group/button-group.tsx:27]: Hm so this was because I was getting an error `Cannot clone element of null`, as one of the children is conditionally rendered.. I will look into it again, perhaps theres a better way

Comment (mattrussell36) [reply frontend/src/components/button-group/button-group.tsx]: So I believe we absolutely need an if statement here.

Heres the type definition for `child` provided by `React.Children.map`

`(parameter) child: string | number | boolean | {} | React.ReactElement<any, string | React.JSXElementConstructor<any>> | React.ReactPortal | null | undefined`

null and undefined are valid react children but _not_ valid arguments for React.cloneElement. I'd like the ButtonGroup component be able to accept null or undefined children so that we can optionally render some children within ButtonGroup ([see here](https://github.com/vegaprotocol/vegawallet-desktop/blob/40f0bca90037412a228b6630ade98553c7bdc486/frontend/src/components/onboard/onboard.tsx#L92)). 

In those cases if the child is null we simply want to omit it.

To make this clearer if changed from checking truthy-ness of child and instead used React.isValidElement.

File: backend/handler.go [hunk 3]
```diff
@@ -95,47 +93,48 @@ func (h *Handler) IsAppInitialised() (bool, error) {
...
-	svcStore, err := svcstore.InitialiseStore(paths.New(cfg.VegaHome))
-	if err != nil {
-		return false, fmt.Errorf("couldn't initialise service store: %w", err)
-	}
+// SearchForExistingConfiguration searches for existing wallets and networks.
+// This endpoint should be used to help the user to restore existing wallet
+// setup in the app.
+func (h *Handler) SearchForExistingConfiguration() (*SearchForExistingConfigurationResponse, error) {
+	h.log.Debug("Entering ListWallets")
+	defer h.log.Debug("Leaving ListWallets")
```
Comment (dexturr) [inline backend/handler.go:109]:
```suggestion
	h.log.Debug("Entering SearchForExistingConfiguration")
	defer h.log.Debug("Leaving SearchForExistingConfiguration")
```

**Review by dexturr — APPROVED** [review]
