### PR TITLE
Fix/262: Network switch warning

### LINKED ISSUE #262: Updating network requires refreshing Console to connect
## Tasks 

- [ ] Implement popup to explain what you need to do after updating a network e.g. "Updating the network will lose your existing wallet connections. Reset your wallet app to continue..."
- [ ] Talk to Matt about how to handle this in the dapp front end (if anything)

## Software information
Build info:
- Version: 0.2.1

**Tips:** You can get this information from the window located under the `File > About Vegawallet`.

Installation:
- [x] I downloaded it from the GitHub releases page.
- [ ] I built it from my local repository (`wails build`)

# Problem encountered
When updating a network config by overwriting an existing network with new config via URL, you need to disconnect from fairground console (v1 & v2), and the desktop wallet in order to get the apps to work with the correct nodes (and stop the DW from crashing).

# Expected behaviour
Updating network details in the wallet should automatically restart the wallet service and ask you to reconnect your wallet in the dApps. 

# Evidence
see comment below

### PR DESCRIPTION
**Pull request by notbot00**
Closes #262 

Displays a warning when there are active connections in any of the wallets, and the user tries switching networks.

Screenshot 2022-10-28 at 13 25 46

### CODE REVIEW

File: frontend/src/components/network-switcher/connections-warning-dialog.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
+import { Button } from '../button'
+import { ButtonGroup } from '../button-group'
+import { ButtonUnstyled } from '../button-unstyled'
+import { Dialog } from '../dialog'
+import { Warning } from '../icons/warning'
+
+const WarningPrompt = ({ wallets }: { wallets: string[] }) => {
+  if (wallets.length > 1) {
+    ;<p>
```
Comment (mattrussell36) [inline frontend/src/components/network-switcher/connections-warning-dialog.tsx:9]: chore (blocking): return here?

File: frontend/src/components/network-switcher/network-switcher.tsx [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+export const NetworkSwitcher = () => {
+  const { state, actions, dispatch } = useGlobal()
+  const [hasConnectionWarning, setConnectionWarning] = useState(false)
+  const [selectedNetwork, setSelectedNetwork] = useState(state.network)
+  const activeConnections = useMemo(
+    () => findActiveConnections(state.wallets),
+    [state.wallets]
+  )
+
+  console.log(activeConnections)
```
Comment (mattrussell36) [inline frontend/src/components/network-switcher/network-switcher.tsx:32]: chore (blocking): Stray log

Comment (notbot00) [reply frontend/src/components/network-switcher/network-switcher.tsx]: fixed, thanks!

File: frontend/src/components/network-switcher/connections-warning-dialog.tsx (hunk 1 above)
Comment (notbot00) [reply frontend/src/components/network-switcher/connections-warning-dialog.tsx]: ugh, thanks, good catch, fixed
